/*-----------   PARTIE PARAMETRAGE    */
create table MARQUE(
MAR_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
MAR_CODE varchar(5),
MAR_LIBELLE varchar(20),
);
create table MODELE(
MOD_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
MOD_CODE varchar(5),
MOD_LIBELLE varchar(20),
MOD_IDMARQUE INT(6) UNSIGNED,
FOREIGN KEY (MOD_IDMARQUE) REFERENCES MARQUE(MAR_ID) 
);
create table STATUT(
STA_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
STA_CODE varchar(5),
STA_LIBELLE varchar(20),
);
/*------------ FIN PARTIE PARAMETRAGE*/
create table AGENCE(
AGEN_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
AGEN_CODE varchar(20),
AGEN_ADRESSE1 varchar(60),
AGEN_ADRESSE2 varchar(60),
AGEN_ADRESSE3 varchar(60),
AGEN_CP Integer,
AGEN_VILLE varchar(20)
);
create table GARAGE(
GAR_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
GAR_CODE varchar(20),
GAR_NOM varchar(20),
GAR_TYPE varchar(20),
GAR_GERANTNOM varchar(60),
GAR_GERPRENOM varchar(60),
GAR_NUMTEL1 varchar(20),
GAR_NUMTEL2 varchar(20),
GAR_MAIL varchar(30)
);
create table CORRESPONDANTVOITURE(
CV_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
CV_NOM varchar(20),
CV_PRENOM varchar(20),
CV_NUMTEL1 varchar(20),
CV_NUMTEL2 varchar(20),
CV_MAIL varchar(30),
CV_IDAGENCE INT(6) UNSIGNED,
CV_IDVEHICULE INT(6),
FOREIGN KEY (CV_IDAGENCE) REFERENCES AGENCE(AGEN_ID)
);
create table VEHICULE(
VEH_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
VEH_IMMATRICULATION varchar(20),
VEH_IDMARQUE INT(6) UNSIGNED,
VEH_IDMODELE INT(6) UNSIGNED,
VEH_DATEMISEENSERVICE varchar(20),
VEH_CTDATE varchar(20),
VEH_REVISIONDATE varchar(20),
VEH_COMPTERENDUREVISION varchar(20),
VEH_TAUXPOLLUTION varchar(20),
VEH_KMPARCOURU varchar(20),
VEH_ETATBATTERRIE varchar(20),
VEH_DONNEESVEHICULE varchar(20),
VEH_IDSTATUT INT(6) UNSIGNED,
VEH_IDAGENCE INT(6) UNSIGNED,
CV_IDCV INT(6) UNSIGNED,
FOREIGN KEY (VEH_IDMARQUE) REFERENCES MARQUE(MAR_ID),
FOREIGN KEY (VEH_IDMODELE) REFERENCES MODELE(MOD_ID),
FOREIGN KEY (VEH_IDSTATUT) REFERENCES STATUT(STA_ID),
FOREIGN KEY (VEH_IDAGENCE) REFERENCES AGENCE(AGEN_ID),
FOREIGN KEY (CV_IDCV) REFERENCES CORRESPONDANTVOITURE(CV_ID)
);
create table DOCUMENT_VEHICULE(
DV_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DV_NOM varchar(20),
DV_TYPE varchar(20),
DV_CHEMIN varchar(60),
DV_IDVEHICULE INT(6) UNSIGNED,
DV_IDAGENCE  INT(6) UNSIGNED,
FOREIGN KEY (DV_IDAGENCE) REFERENCES AGENCE(AGEN_ID),
FOREIGN KEY (DV_IDVEHICULE) REFERENCES VEHICULE(VEH_ID)
);

