package com.superCar.superCar.model.entities;
// Generated 16 nov. 2017 22:03:34 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Correspondantvoiture generated by hbm2java
 */
@Entity
@Table(name = "CORRESPONDANTVOITURE", catalog = "enidis")
public class Correspondantvoiture implements java.io.Serializable {

	private Integer cvId;
	private Agence agence;
	private String cvNom;
	private String cvPrenom;
	private String cvNumtel1;
	private String cvNumtel2;
	private String cvMail;
	private Integer cvIdvehicule;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public Correspondantvoiture() {
	}

	public Correspondantvoiture(Agence agence, String cvNom, String cvPrenom, String cvNumtel1, String cvNumtel2,
			String cvMail, Integer cvIdvehicule, Set<Vehicule> vehicules) {
		this.agence = agence;
		this.cvNom = cvNom;
		this.cvPrenom = cvPrenom;
		this.cvNumtel1 = cvNumtel1;
		this.cvNumtel2 = cvNumtel2;
		this.cvMail = cvMail;
		this.cvIdvehicule = cvIdvehicule;
		this.vehicules = vehicules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CV_ID", unique = true, nullable = false)
	public Integer getCvId() {
		return this.cvId;
	}

	public void setCvId(Integer cvId) {
		this.cvId = cvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CV_IDAGENCE")
	public Agence getAgence() {
		return this.agence;
	}

	public void setAgence(Agence agence) {
		this.agence = agence;
	}

	@Column(name = "CV_NOM", length = 20)
	public String getCvNom() {
		return this.cvNom;
	}

	public void setCvNom(String cvNom) {
		this.cvNom = cvNom;
	}

	@Column(name = "CV_PRENOM", length = 20)
	public String getCvPrenom() {
		return this.cvPrenom;
	}

	public void setCvPrenom(String cvPrenom) {
		this.cvPrenom = cvPrenom;
	}

	@Column(name = "CV_NUMTEL1", length = 20)
	public String getCvNumtel1() {
		return this.cvNumtel1;
	}

	public void setCvNumtel1(String cvNumtel1) {
		this.cvNumtel1 = cvNumtel1;
	}

	@Column(name = "CV_NUMTEL2", length = 20)
	public String getCvNumtel2() {
		return this.cvNumtel2;
	}

	public void setCvNumtel2(String cvNumtel2) {
		this.cvNumtel2 = cvNumtel2;
	}

	@Column(name = "CV_MAIL", length = 30)
	public String getCvMail() {
		return this.cvMail;
	}

	public void setCvMail(String cvMail) {
		this.cvMail = cvMail;
	}

	@Column(name = "CV_IDVEHICULE")
	public Integer getCvIdvehicule() {
		return this.cvIdvehicule;
	}

	public void setCvIdvehicule(Integer cvIdvehicule) {
		this.cvIdvehicule = cvIdvehicule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "correspondantvoiture")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
