package com.superCar.superCar.model.entities;
// Generated 16 nov. 2017 22:03:34 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Garage generated by hbm2java
 */
@Entity
@Table(name = "GARAGE", catalog = "enidis")
public class Garage implements java.io.Serializable {

	private Integer garId;
	private String garCode;
	private String garNom;
	private String garType;
	private String garGerantnom;
	private String garGerprenom;
	private String garNumtel1;
	private String garNumtel2;
	private String garMail;

	public Garage() {
	}

	public Garage(String garCode, String garNom, String garType, String garGerantnom, String garGerprenom,
			String garNumtel1, String garNumtel2, String garMail) {
		this.garCode = garCode;
		this.garNom = garNom;
		this.garType = garType;
		this.garGerantnom = garGerantnom;
		this.garGerprenom = garGerprenom;
		this.garNumtel1 = garNumtel1;
		this.garNumtel2 = garNumtel2;
		this.garMail = garMail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GAR_ID", unique = true, nullable = false)
	public Integer getGarId() {
		return this.garId;
	}

	public void setGarId(Integer garId) {
		this.garId = garId;
	}

	@Column(name = "GAR_CODE", length = 20)
	public String getGarCode() {
		return this.garCode;
	}

	public void setGarCode(String garCode) {
		this.garCode = garCode;
	}

	@Column(name = "GAR_NOM", length = 20)
	public String getGarNom() {
		return this.garNom;
	}

	public void setGarNom(String garNom) {
		this.garNom = garNom;
	}

	@Column(name = "GAR_TYPE", length = 20)
	public String getGarType() {
		return this.garType;
	}

	public void setGarType(String garType) {
		this.garType = garType;
	}

	@Column(name = "GAR_GERANTNOM", length = 60)
	public String getGarGerantnom() {
		return this.garGerantnom;
	}

	public void setGarGerantnom(String garGerantnom) {
		this.garGerantnom = garGerantnom;
	}

	@Column(name = "GAR_GERPRENOM", length = 60)
	public String getGarGerprenom() {
		return this.garGerprenom;
	}

	public void setGarGerprenom(String garGerprenom) {
		this.garGerprenom = garGerprenom;
	}

	@Column(name = "GAR_NUMTEL1", length = 20)
	public String getGarNumtel1() {
		return this.garNumtel1;
	}

	public void setGarNumtel1(String garNumtel1) {
		this.garNumtel1 = garNumtel1;
	}

	@Column(name = "GAR_NUMTEL2", length = 20)
	public String getGarNumtel2() {
		return this.garNumtel2;
	}

	public void setGarNumtel2(String garNumtel2) {
		this.garNumtel2 = garNumtel2;
	}

	@Column(name = "GAR_MAIL", length = 30)
	public String getGarMail() {
		return this.garMail;
	}

	public void setGarMail(String garMail) {
		this.garMail = garMail;
	}

}
