package com.superCar.superCar.model.entities;
// Generated 16 nov. 2017 22:03:34 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name = "MARQUE", catalog = "enidis")
public class Marque implements java.io.Serializable {

	private Integer marId;
	private String marCode;
	private String marLibelle;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);
	private Set<Modele> modeles = new HashSet<Modele>(0);

	public Marque() {
	}

	public Marque(String marCode, String marLibelle, Set<Vehicule> vehicules, Set<Modele> modeles) {
		this.marCode = marCode;
		this.marLibelle = marLibelle;
		this.vehicules = vehicules;
		this.modeles = modeles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAR_ID", unique = true, nullable = false)
	public Integer getMarId() {
		return this.marId;
	}

	public void setMarId(Integer marId) {
		this.marId = marId;
	}

	@Column(name = "MAR_CODE", length = 5)
	public String getMarCode() {
		return this.marCode;
	}

	public void setMarCode(String marCode) {
		this.marCode = marCode;
	}

	@Column(name = "MAR_LIBELLE", length = 20)
	public String getMarLibelle() {
		return this.marLibelle;
	}

	public void setMarLibelle(String marLibelle) {
		this.marLibelle = marLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marque")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marque")
	public Set<Modele> getModeles() {
		return this.modeles;
	}

	public void setModeles(Set<Modele> modeles) {
		this.modeles = modeles;
	}

}
