package com.superCar.superCar.model.entities;
// Generated 16 nov. 2017 22:03:34 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statut generated by hbm2java
 */
@Entity
@Table(name = "STATUT", catalog = "enidis")
public class Statut implements java.io.Serializable {

	private Integer staId;
	private String staCode;
	private String staLibelle;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public Statut() {
	}

	public Statut(String staCode, String staLibelle, Set<Vehicule> vehicules) {
		this.staCode = staCode;
		this.staLibelle = staLibelle;
		this.vehicules = vehicules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STA_ID", unique = true, nullable = false)
	public Integer getStaId() {
		return this.staId;
	}

	public void setStaId(Integer staId) {
		this.staId = staId;
	}

	@Column(name = "STA_CODE", length = 5)
	public String getStaCode() {
		return this.staCode;
	}

	public void setStaCode(String staCode) {
		this.staCode = staCode;
	}

	@Column(name = "STA_LIBELLE", length = 20)
	public String getStaLibelle() {
		return this.staLibelle;
	}

	public void setStaLibelle(String staLibelle) {
		this.staLibelle = staLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statut")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
