package com.superCar.superCar.model.entities;
// Generated 16 nov. 2017 22:03:34 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name = "VEHICULE", catalog = "enidis")
public class Vehicule implements java.io.Serializable {

	private Integer vehId;
	private Agence agence;
	private Correspondantvoiture correspondantvoiture;
	private Marque marque;
	private Modele modele;
	private Statut statut;
	private String vehImmatriculation;
	private String vehDatemiseenservice;
	private String vehCtdate;
	private String vehRevisiondate;
	private String vehCompterendurevision;
	private String vehTauxpollution;
	private String vehKmparcouru;
	private String vehEtatbatterrie;
	private String vehDonneesvehicule;
	private Set<DocumentVehicule> documentVehicules = new HashSet<DocumentVehicule>(0);

	public Vehicule() {
	}

	public Vehicule(Agence agence, Correspondantvoiture correspondantvoiture, Marque marque, Modele modele,
			Statut statut, String vehImmatriculation, String vehDatemiseenservice, String vehCtdate,
			String vehRevisiondate, String vehCompterendurevision, String vehTauxpollution, String vehKmparcouru,
			String vehEtatbatterrie, String vehDonneesvehicule, Set<DocumentVehicule> documentVehicules) {
		this.agence = agence;
		this.correspondantvoiture = correspondantvoiture;
		this.marque = marque;
		this.modele = modele;
		this.statut = statut;
		this.vehImmatriculation = vehImmatriculation;
		this.vehDatemiseenservice = vehDatemiseenservice;
		this.vehCtdate = vehCtdate;
		this.vehRevisiondate = vehRevisiondate;
		this.vehCompterendurevision = vehCompterendurevision;
		this.vehTauxpollution = vehTauxpollution;
		this.vehKmparcouru = vehKmparcouru;
		this.vehEtatbatterrie = vehEtatbatterrie;
		this.vehDonneesvehicule = vehDonneesvehicule;
		this.documentVehicules = documentVehicules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VEH_ID", unique = true, nullable = false)
	public Integer getVehId() {
		return this.vehId;
	}

	public void setVehId(Integer vehId) {
		this.vehId = vehId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEH_IDAGENCE")
	public Agence getAgence() {
		return this.agence;
	}

	public void setAgence(Agence agence) {
		this.agence = agence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CV_IDCV")
	public Correspondantvoiture getCorrespondantvoiture() {
		return this.correspondantvoiture;
	}

	public void setCorrespondantvoiture(Correspondantvoiture correspondantvoiture) {
		this.correspondantvoiture = correspondantvoiture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEH_IDMARQUE")
	public Marque getMarque() {
		return this.marque;
	}

	public void setMarque(Marque marque) {
		this.marque = marque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEH_IDMODELE")
	public Modele getModele() {
		return this.modele;
	}

	public void setModele(Modele modele) {
		this.modele = modele;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEH_IDSTATUT")
	public Statut getStatut() {
		return this.statut;
	}

	public void setStatut(Statut statut) {
		this.statut = statut;
	}

	@Column(name = "VEH_IMMATRICULATION", length = 20)
	public String getVehImmatriculation() {
		return this.vehImmatriculation;
	}

	public void setVehImmatriculation(String vehImmatriculation) {
		this.vehImmatriculation = vehImmatriculation;
	}

	@Column(name = "VEH_DATEMISEENSERVICE", length = 20)
	public String getVehDatemiseenservice() {
		return this.vehDatemiseenservice;
	}

	public void setVehDatemiseenservice(String vehDatemiseenservice) {
		this.vehDatemiseenservice = vehDatemiseenservice;
	}

	@Column(name = "VEH_CTDATE", length = 20)
	public String getVehCtdate() {
		return this.vehCtdate;
	}

	public void setVehCtdate(String vehCtdate) {
		this.vehCtdate = vehCtdate;
	}

	@Column(name = "VEH_REVISIONDATE", length = 20)
	public String getVehRevisiondate() {
		return this.vehRevisiondate;
	}

	public void setVehRevisiondate(String vehRevisiondate) {
		this.vehRevisiondate = vehRevisiondate;
	}

	@Column(name = "VEH_COMPTERENDUREVISION", length = 20)
	public String getVehCompterendurevision() {
		return this.vehCompterendurevision;
	}

	public void setVehCompterendurevision(String vehCompterendurevision) {
		this.vehCompterendurevision = vehCompterendurevision;
	}

	@Column(name = "VEH_TAUXPOLLUTION", length = 20)
	public String getVehTauxpollution() {
		return this.vehTauxpollution;
	}

	public void setVehTauxpollution(String vehTauxpollution) {
		this.vehTauxpollution = vehTauxpollution;
	}

	@Column(name = "VEH_KMPARCOURU", length = 20)
	public String getVehKmparcouru() {
		return this.vehKmparcouru;
	}

	public void setVehKmparcouru(String vehKmparcouru) {
		this.vehKmparcouru = vehKmparcouru;
	}

	@Column(name = "VEH_ETATBATTERRIE", length = 20)
	public String getVehEtatbatterrie() {
		return this.vehEtatbatterrie;
	}

	public void setVehEtatbatterrie(String vehEtatbatterrie) {
		this.vehEtatbatterrie = vehEtatbatterrie;
	}

	@Column(name = "VEH_DONNEESVEHICULE", length = 20)
	public String getVehDonneesvehicule() {
		return this.vehDonneesvehicule;
	}

	public void setVehDonneesvehicule(String vehDonneesvehicule) {
		this.vehDonneesvehicule = vehDonneesvehicule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicule")
	public Set<DocumentVehicule> getDocumentVehicules() {
		return this.documentVehicules;
	}

	public void setDocumentVehicules(Set<DocumentVehicule> documentVehicules) {
		this.documentVehicules = documentVehicules;
	}

}
